version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: factura-db
    environment:
      POSTGRES_DB: factura
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminsan
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: